### ISSUE TITLE
欧洲杯脚本报错了呀

### ISSUE THREAD

**Issue by BIGBbox** [Tsukasa007/my_script#1]
账号1欧洲杯助力码为 undefined
"NOTLOGIN"
"NOTLOGIN"
"NOTLOGIN"
"NOTLOGIN"
"NOTLOGIN"
未登录

❗️狂欢欧洲杯, 错误!
TypeError: Cannot read property 'length' of undefined
    at /ql/scripts/Tsukasa007_my_script_jd_europeancup.js:78:46
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

🔔狂欢欧洲杯, 结束! 🕛 17.76 秒

**Comment by Tsukasa007** [comment]
修复好了
