### ISSUE TITLE
大佬，新活动，七夕会员福利社开卡

### ISSUE THREAD

**Issue by EchoChan314** [Tsukasa007/my_script#10]
复制别人的：22.0复制整段话 http:/JesR0BMlSy9fRA 免费抽万元大奖 千万京豆#A2MRJ4imQb@咑開京岽app

**Comment by Tsukasa007** [comment]
这个活动要开好多卡的哦

**Comment by EchoChan314** [comment]
已有其它大佬开发，谢谢。
https://raw.githubusercontent.com/smiek2221/scripts/master/gua_opencard7.js

**Comment by Tsukasa007** [comment]
好👌
