### ISSUE TITLE
汪汪乐园养joy一直限流的问题

### ISSUE THREAD

**Issue by KuHai-A** [Tsukasa007/my_script#2]
我看好像是遇到限流了就无限重试，这个日志太长太大了，是否可以加个变量，设定重试X后就跳过合成了，开始后面的步骤了

**Comment by Tsukasa007** [comment]
但是不合成就无法进行下一步了，我设置一个wait 吧&nbsp; 3秒合成一次，这个合成经常限流的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 上午10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Tsukasa007/my_script] 汪汪乐园养joy一直限流的问题 (#2)





 
我看好像是遇到限流了就无限重试，这个日志太长太大了，是否可以加个变量，设定重试X后就跳过合成了，开始后面的步骤了

**Comment by Tsukasa007** [comment]
优化好了

**Comment by KuHai-A** [comment]
> 优化好了

大老牛啊！我还说晚上回去简单研究下呢~~
大佬有没有tg群组，拉一手啊

**Comment by Tsukasa007** [comment]
暂时github交流吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午4:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tsukasa007/my_script] 汪汪乐园养joy一直限流的问题 (#2)





  
优化好了
  
大老牛啊！我还说晚上回去简单研究下呢~~
 大佬有没有tg群组，拉一手啊

**Comment by KuHai-A** [comment]
![QQ截图20210707161817](https://user-images.githubusercontent.com/37091493/124725051-21ec4c80-df3f-11eb-9460-66078353c8b9.png)
这个变量写错了，大佬修复下吧，然后拉库跑起来了

**Comment by Tsukasa007** [comment]
可以了
