### ISSUE TITLE
joy满后518错误

### ISSUE THREAD

**Issue by aidu1001** [Tsukasa007/my_script#4]
因为使用了之前最大化设置，手上joy满后购买出现518错误，然后手上等级一样的joy，不会合成。然后一直这样循环下去，

**Comment by aidu1001** [comment]
购买错误：519是钱不够，518是joy满了，无法购买

**Comment by Tsukasa007** [comment]
没做回收，那我加上吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月9日(星期五) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Tsukasa007/my_script] joy满后518错误 (#4)





 
购买错误：519是钱不够，518是joy满了，无法购买

**Comment by aidu1001** [comment]
感谢大佬。不然号多的时候，实在不好通知一个个手动处理。

**Comment by Tsukasa007** [comment]
对，所以我还是把瞎买模式关了

**Comment by Tsukasa007** [comment]
好了不过没测试过，我这里没这种情况

**Comment by aidu1001** [comment]
感谢，我测试一下

**Comment by Tsukasa007** [comment]
最大收益默认是关的了，感觉没收益多少，早知道不搞了

**Comment by aidu1001** [comment]
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
"The `GET` method cannot be used with a body"
汪汪乐园养joy API请求失败，请检查网路重试

❗️汪汪乐园养joy, 错误!
TypeError: Cannot read property 'success' of undefined
    at /jd/scripts/jd_joy_park_joy.js:334:37
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
完成！

**Comment by aidu1001** [comment]
最大收益这个功能。真算多于的。实际购买低级joy，不会增加收益。后面低级joy特别贵。

**Comment by Tsukasa007** [comment]
好了 忘记改post了

**Comment by aidu1001** [comment]
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
回收🐶 失败！【undefined】 code=10

❗️汪汪乐园养joy, 错误!
TypeError: Cannot read property 'success' of undefined
    at /jd/scripts/jd_joy_park_joy.js:334:37
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
完成！

**Comment by aidu1001** [comment]
回收时，没取到数据

**Comment by Tsukasa007** [comment]
🤔 我看看

**Comment by Tsukasa007** [comment]
再试试 应该ok了

**Comment by aidu1001** [comment]
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
回收🐶 失败！【undefined】 code=10

❗️汪汪乐园养joy, 错误!
TypeError: Cannot read property 'success' of undefined
    at /jd/scripts/jd_joy_park_joy.js:334:37
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
完成！


还是一样哦。joy等级有取到。但doJoyBuy在处理时，没有取到id的感觉。

**Comment by Tsukasa007** [comment]
😯

**Comment by aidu1001** [comment]
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
aaaaaaaaaaaaaaa: 2026
回收🐶 失败！【undefined】 code=10

❗️汪汪乐园养joy, 错误!
TypeError: Cannot read property 'success' of undefined
    at /jd/scripts/jd_joy_park_joy.js:335:37
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
完成！
。。


有取到joy的id-_-!!!

**Comment by Tsukasa007** [comment]
你确定最新不

**Comment by aidu1001** [comment]
我错了。刚更新了。。出现死循环

工位清理完成！
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
回收🐶 成功！
购买joy level: 2 成功！  code的意思是=【OK】
购买joy level: 2 成功！  code的意思是=【没空位】
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
回收🐶 成功！
购买joy level: 2 成功！  code的意思是=【OK】
购买joy level: 2 成功！  code的意思是=【没空位】
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了
回收🐶 成功！
购买joy level: 2 成功！  code的意思是=【OK】
购买joy level: 2 成功！  code的意思是=【没空位】
因为购买 2级🐶 没空位 所以我要删掉比低级的狗了

**Comment by Tsukasa007** [comment]
哈哈哈哈哈哈哈

**Comment by Tsukasa007** [comment]
快停下 ，等下钱花完了哈哈哈哈哈哈哈哈

**Comment by aidu1001** [comment]
看到就停了。。大佬有毒。

**Comment by aidu1001** [comment]
if (joyRecoveryFlag.success) {
                  //data = await doJoyBuy(level)
                }

我把这个，注示就可以了。。感谢大佬

**Comment by Tsukasa007** [comment]
对

**Comment by Tsukasa007** [comment]
这个删掉就行了

**Comment by aidu1001** [comment]
-_-跑一次后。准备把删除功能也B了，太可怕了。。

**Comment by Tsukasa007** [comment]
没有最大化 就不会有这种情况了的
